### ISSUE TITLE
同一个服务器macbook翻不了air可以

### ISSUE THREAD

**Issue by verck** [CoderJin/ssrconnect#11]
如题。为什么02年air可以翻15年macbook没用。

**Comment by verck** [comment]
补充一句win10也可以

**Comment by CoderJin** [comment]
你看看 是不是你环境的问题

**Comment by verck** [comment]
不太确定你环境指的什么，可是我air  macbook 和win10连的是同一个路由。用的也是同一个vps并且两台macos用的都是你这个

**Comment by CoderJin** [comment]
能远程看一下不？

**Comment by verck** [comment]
可以啊，怎么做？

**Comment by CoderJin** [comment]
TeamViewer 下一个这个

**Comment by CoderJin** [comment]
TeamViewer 下一个这个

**Comment by verck** [comment]
然后呢

**Comment by verck** [comment]
。。。突然间又可以了。什么都没做就是下载了teamviewer两台都可以。
