### ISSUE TITLE
关于Ssrconnectpro服务器ip的疑问

### ISSUE THREAD

**Issue by frank202020** [CoderJin/ssrconnect#14]
作者您好，感谢您开发的这个app，今天测试了一下，可以用。但是我有一个小小的疑问，为什么ssrconnectpro连接之后，在手机设置，VPN连接，进去之后看到的服务器IP是11.11.11.11，指定的ip地址是192.169.88.88？能帮忙解答一下疑惑吗，谢谢

**Comment by CoderJin** [comment]
这个可以随便写的
