### ISSUE TITLE
成功连接了vpn但是没法用

### ISSUE THREAD

**Issue by KumamanoRachel** [CoderJin/ssrconnect#18]
扫描了我购买的shadowsocks的一个节点二维码，手机也显示连接了vpn，但是还是刷不出ins或者别的需要翻墙的网址

**Comment by CoderJin** [comment]
那你在pc能正常使用不？

**Comment by CoderJin** [comment]
好了 没 哥们 能正常使用不？

**Comment by KumamanoRachel** [comment]
我买的shadowsocks pc端正常能用的，手机现在还是用不了

**Comment by CoderJin** [comment]
方便贴出 你账号和密码不 还有端口 或者邮箱告诉我

**Comment by KumamanoRachel** [comment]
你给我一个邮箱，我私信你？

**Comment by CoderJin** [comment]
2821201279@qq.com

**Comment by samchloe** [comment]
扫描了我购买的shadowsocks的一个节点二维码，手机也显示连接了vpn，但是还是刷不出ins或者别的需要翻墙的网址，尝试了几次都不行

**Comment by CoderJin** [comment]
方便把你你二维码发给我不？

**Comment by samchloe** [comment]
求帮助解决方法，手机显示vpn连接成功 但是还是刷不了ins😭😭😭

**Comment by CoderJin** [comment]
@samchloe  方便二维码发给我不？ 我看看是不是你服务器的问题？

**Comment by samchloe** [comment]
你好 我已经发了二维码给你啦，你们有微信客服号或qq客服号咨询的吗？

**Comment by CoderJin** [comment]
@samchloe  我没有买服务,我不知道你用的是哪一家的服务，我可以帮你看看？具体是什么原因？请发到我的QQ邮箱2821201279@qq.com
