### ISSUE TITLE
二维码功能几乎不可用

### ISSUE THREAD

**Issue by mymartin** [CoderJin/ssrconnect#2]
想要通过扫描二维码的方式配置
但是无论是调用摄像头还是识别照片中的二维码都不成功
***
具体表现为：
扫描屏幕上的二维码显示“error RQ”

![img_3033](https://user-images.githubusercontent.com/6276117/27781959-fc3d0c32-6002-11e7-89f2-b98d6ecdefc9.PNG)

**Comment by CoderJin** [comment]
具体什么二维码 能看看不？

**Comment by mymartin** [comment]
http://ss.ishadowx.com/
就是这个网站上的。

发自我的 iPhone

在 2017年7月3日，下午3:45，CoderJin <notifications@github.com<mailto:notifications@github.com>> 写道：


具体什么二维码 能看看不？

**Comment by CoderJin** [comment]
谢谢 反馈 已解决，下次返回其他问题，请帮忙及时反馈 谢谢

**Comment by CoderJin** [comment]
请更新一下最新版本2.3.8 试试
