### ISSUE TITLE
请问如何在Window7上设置使用？只有mac版吗？

### ISSUE THREAD

**Issue by Josephif** [CoderJin/ssrconnect#3]
请问如何在Window7上设置使用？只有mac版吗？
输入网址和密码后提示错误868。

**Comment by CoderJin** [comment]
为啥会有868提示,你这个868提示是服务端那边吗?,客户端好像我从来没有遇到过这种提示

**Comment by Josephif** [comment]
我是用的win7网络设置的vpn，
服务器地址写：usav2.fatiaoss.net
只有密码请问用户名该怎么写？

小飞机没听说过，您能细说下win7的教程吗？感谢！

**Comment by CoderJin** [comment]
你说的是ios上面还是mac上面的 !

**Comment by CoderJin** [comment]
ios 上面的用户名随便填写。

**Comment by Josephif** [comment]
是索尼笔记本windows7上设置！
手机我已经成功连接没问题的，就想让win7笔记本用上

**Comment by CoderJin** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases
