### ISSUE TITLE
怎么连ssr？

### ISSUE THREAD

**Issue by udon0818** [CoderJin/ssrconnect#30]
软件中只有加密一个选，混淆、协议这些呢？

**Comment by CoderJin** [comment]
什么混淆方式？

**Comment by udon0818** [comment]
ssr除了method，不是还有protocol、obfs这些属性设置吗？你的这个app好像只有method。
我现在只能把端口的协议和混淆设为origin和plain，以ss的方式连接

**Comment by CoderJin** [comment]
只支持origin和plain
