### ISSUE TITLE
请问能否指导增加whatsapp走代理

### ISSUE THREAD

**Issue by yeds11** [CoderJin/ssrconnect#32]
测试连接正常，FB/T/YT都能正常使用，就是whatsapp不能走代理，麻烦你能否指导一下，感谢！

**Comment by CoderJin** [comment]
这个我已经在处理中，只是时间的问题

**Comment by CoderJin** [comment]
https://itunes.apple.com/cn/app/connectplus-proxy-utility/id1344505630?mt=8 新的app  whatsapp 能使用的
