### ISSUE TITLE
mac air 安装以后打不开

### ISSUE THREAD

**Issue by Jackwanguestc** [CoderJin/ssrconnect#33]
想用ss，用的mac air，iOS 10.11.3
装好以后打不开是什么情况啊，毕竟花钱买的，求售后啊。

**Comment by CoderJin** [comment]
不对啊 这个应该没啥问题的 您是下载我的mac ssrconnect

**Comment by Jackwanguestc** [comment]
是装的mac版啊，iphone不是免费吗。
点了图标没反应，会是什么原因呢，以前没用过iOS。

**Comment by CoderJin** [comment]
具体情况 我要看的，你那个原因我也不清楚

**Comment by CoderJin** [comment]
现在的mac 最新版系统是10.13.2  这个由尝试过没

**Comment by Jackwanguestc** [comment]
没有，不太想升级系统。
主要是他也没报错，就是没反应，我需要设置什么，或者我这里能看到log信息吗

**Comment by CoderJin** [comment]
能看到日志的，我也不知道具体是什么原因，这个要看日志的。

**Comment by CoderJin** [comment]
应该是兼容的问题，你那个版本的系统我不记得，当初有没有有去测试了

**Comment by Jackwanguestc** [comment]
你看看是这个嘛，有什么问题。
Process:               SsrConnect [725]
Path:                  /Applications/SsrConnect.app/Contents/MacOS/SsrConnect
Identifier:            cn.likejin.www.ssrconnecReal
Version:               1.2.3 (17101703)
App Item ID:           1217575505
App External ID:       824045153
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SsrConnect [725]
User ID:               501

Date/Time:             2018-01-02 17:12:40.670 +0800
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        E5D48472-4647-5A32-1B98-9B1D1EAF4A3F

Sleep/Wake UUID:       474EA3AD-34FC-45B7-B224-0CF16F167A02

Time Awake Since Boot: 10000 seconds
Time Since Wake:       7700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000104e6f000
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:
-0 sec           	CODE SIGNING: cs_invalid_page(0x104e6f000): p=725[SsrConnect] final status 0x3004200, denying page sending SIGKILL
-0 sec           	CODE SIGNING: process 725[SsrConnect]: rejecting invalid page at address 0x104e6f000 from offset 0x0 in file "/Applications/SsrConnect.app/Contents/Frameworks/MMWormhole.framework/Versions/A/MMWormhole" (cs_mtime:1508279747.0 == mtime:1508279747.0) (signed:1 validated:1 tainted:1 wpmapped:0 slid:0)

VM Regions Near 0x104e6f000:
    __LINKEDIT             0000000104e52000-0000000104e6f000 [  116K] r--/rwx SM=COW  /Applications/SsrConnect.app/Contents/MacOS/SsrConnect
--> mapped file            0000000104e6f000-0000000104e70000 [    4K] r-x/r-x SM=PRV  ,
    Process Corpse Info    0000000104e70000-0000000105070000 [ 2048K] rw-/rwx SM=COW  

Application Specific Information:
dyld: launch, loading dependent libraries
@rpath/MMWormhole.framework/Versions/A/MMWormhole

Thread 0 Crashed:
0   dyld                          	0x00007fff6c712a70 memcmp + 208
1   dyld                          	0x00007fff6c6ff975 ImageLoaderMachO::validateFirstPages(linkedit_data_command const*, int, unsigned char const*, unsigned long, long long, ImageLoader::LinkContext const&) + 145
2   dyld                          	0x00007fff6c704beb ImageLoaderMachOCompressed::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, unsigned int, unsigned int, linkedit_data_command const*, encryption_info_command const*, ImageLoader::LinkContext const&) + 283
3   dyld                          	0x00007fff6c6feadf ImageLoaderMachO::instantiateFromFile(char const*, int, unsigned char const*, unsigned long long, unsigned long long, stat const&, ImageLoader::LinkContext const&) + 299
4   dyld                          	0x00007fff6c6f18c3 dyld::loadPhase6(int, stat const&, char const*, dyld::LoadContext const&) + 402
5   dyld                          	0x00007fff6c6f64d0 dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 710
6   dyld                          	0x00007fff6c6f61f0 dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 180
7   dyld                          	0x00007fff6c6f5c05 dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 762
8   dyld                          	0x00007fff6c6f56aa dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 135
9   dyld                          	0x00007fff6c6f147b dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 213
10  dyld                          	0x00007fff6c6f115f dyld::load(char const*, dyld::LoadContext const&) + 180
11  dyld                          	0x00007fff6c6f676d dyld::libraryLocator(char const*, bool, char const*, ImageLoader::RPathChain const*) + 52
12  dyld                          	0x00007fff6c6fc8ce ImageLoader::recursiveLoadLibraries(ImageLoader::LinkContext const&, bool, ImageLoader::RPathChain const&) + 384
13  dyld                          	0x00007fff6c6fc5d4 ImageLoader::link(ImageLoader::LinkContext const&, bool, bool, bool, ImageLoader::RPathChain const&) + 80
14  dyld                          	0x00007fff6c6f2a12 dyld::link(ImageLoader*, bool, bool, ImageLoader::RPathChain const&) + 149
15  dyld                          	0x00007fff6c6f3bf9 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 3181
16  dyld                          	0x00007fff6c6ef276 dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 512
17  dyld                          	0x00007fff6c6ef036 _dyld_start + 54

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000104e6f000  rcx: 0x0000000000000000  rdx: 0x0000000000000ba0
  rdi: 0x0000000104e6f000  rsi: 0x00007fff5ae8fa20  rbp: 0x00007fff5ae8e8b0  rsp: 0x00007fff5ae8e8b0
   r8: 0x0000000000000003   r9: 0x0000000000000000  r10: 0x0000000000000001  r11: 0x0000000000000202
  r12: 0x0000000000000000  r13: 0x0000000000000003  r14: 0x0000000000000ba0  r15: 0x00007fff6c72fb30
  rip: 0x00007fff6c712a70  rfl: 0x0000000000010246  cr2: 0x0000000104e6f000
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x104d6d000 -        0x104e28fff +cn.likejin.www.ssrconnecReal (1.2.3 - 17101703) <0D454B4D-EE06-34CA-B813-2392C9031188> /Applications/SsrConnect.app/Contents/MacOS/SsrConnect
    0x7fff6c6ee000 -     0x7fff6c725007  dyld (360.19) <9D05FDF4-65CE-3B53-86D4-ABE1A5BF35F3> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 5320
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1176K resident=0K(0%) swapped_out_or_unallocated=1176K(100%)
Writable regions: Total=10.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=10.2M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Process Corpse Info               2048K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                             404K        4 
__LINKEDIT                         200K        3 
__TEXT                             976K        3 
mapped file                          4K        2 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             67.6M       14

**Comment by CoderJin** [comment]
嗯  如果是第三方依赖的问题MMWormhole 的问题，还真需要调试才能处理

**Comment by Jackwanguestc** [comment]
所以没有解决方法吗，还是要升级到那个版本才能用

**Comment by CoderJin** [comment]
反正我能确定的是系统升级到最新肯定没问题，我目前用的系统是10.13.2  完全没有遇到任何问题

**Comment by CoderJin** [comment]
哥们 升级系统没 如果不能升级系统的话，我这边只能安装一个虚拟机试试看了

**Comment by Jackwanguestc** [comment]
大哥，我不想升级啊。不都说升级会卡吗。你试试吧。

**Comment by CoderJin** [comment]
你电脑多大内存的 应该不会卡 ，嗯 我试一下也很慢的，还要下载系统，系统很大，而且还有安装到虚拟机上面

**Comment by CoderJin** [comment]
目前我已经在下载中  下载完了才能进行测试

**Comment by Jackwanguestc** [comment]
邮件发给你了
