### ISSUE TITLE
关于ssr支持

### ISSUE THREAD

**Issue by dark-wind** [CoderJin/ssrconnect#38]
![img_0076](https://user-images.githubusercontent.com/15257951/35470943-50805618-038d-11e8-8122-c12d43482cb6.PNG)

![img_0077](https://user-images.githubusercontent.com/15257951/35470949-6ff650c4-038d-11e8-84ae-40a6455d63ef.PNG)

APP商店看到新特性写的支持ssr，但是type可选只有ss一种，请问应该如何配置

**Comment by CoderJin** [comment]
你看清楚 不明白先理解了 先查查
