### ISSUE TITLE
5s ssrconnectpro显示vpn连接成功，但是无法上外网

### ISSUE THREAD

**Issue by bymzy** [CoderJin/ssrconnect#40]
你好，我的vpn用windows能够连接。
之前用ssrconnect也可以正常连接x墙，但是最近却不能用了。不知道是最近有什么升级之类的吗？ps:朋友的7plus，用相同的vpn可以正常x墙。

**Comment by wangjinwei0806** [comment]
你的配置贴出来 就是服务器的用户名和密码 我看看

**Comment by CoderJin** [comment]
这个我也不知道怎么回事啊 方便把你的服务器配置贴出来 看看不？

**Comment by bymzy** [comment]
184.170.217.7
443
YjljZTc4MT
Aes-256-cfb

发件人: CoderJin [mailto:notifications@github.com]
发送时间: 2018年2月1日 21:33
收件人: CoderJin/ssrconnect <ssrconnect@noreply.github.com>
抄送: mzy <bymzy@outlook.com>; Author <author@noreply.github.com>
主题: Re: [CoderJin/ssrconnect] 5s ssrconnectpro显示vpn连接成功，但是无法上外网 (#40)


这个我也不知道怎么回事啊 方便把你的服务器配置贴出来 看看不？

**Comment by CoderJin** [comment]
我可以正常使用啊

**Comment by bymzy** [comment]
这就尴尬了，，，到底是为啥呢。我朋友也能用，，你用的啥型号的iphone?

**Comment by CoderJin** [comment]
我不知道是不是你密碼輸入錯誤了 你直接扫描二维码试试看

**Comment by CoderJin** [comment]
5s

**Comment by bymzy** [comment]
呃呃呃，重新复制粘贴了下账号，密码，现在可以了。。

谢大神！！！

发件人: CoderJin [mailto:notifications@github.com]
发送时间: 2018年2月2日 11:01
收件人: CoderJin/ssrconnect <ssrconnect@noreply.github.com>
抄送: mzy <bymzy@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [CoderJin/ssrconnect] 5s ssrconnectpro显示vpn连接成功，但是无法上外网 (#40)


5s
