### ISSUE TITLE
国内更新不了了怎么办？

### ISSUE THREAD

**Issue by DearTanker** [CoderJin/ssrconnect#6]

**Comment by CoderJin** [comment]
我更新的时候 有尝试过在国内重新上架，好像上架不了。考虑到这个原因，我已经重新提交了一个版本，也就是新增了一个应用，希望能审核过，到时候你们可以直接使用那个版本了，希望能顺利通过。

**Comment by CoderJin** [comment]
我新的app已经上架了，有需要的话，可以去下载哪一款，和之前的一样的。

**Comment by DearTanker** [comment]
名字？

**Comment by CoderJin** [comment]
ssrconnectpro

**Comment by DearTanker** [comment]
搜索不到。直接丢链接吧，谢谢。

**Comment by CoderJin** [comment]
https://itunes.apple.com/cn/app/ssrconnectpro/id1272045249?l=zh&ls=1&mt=8

**Comment by DearTanker** [comment]
暂时搜索不到。估计还没有更新索引吧。

**Comment by CoderJin** [comment]
连接也打不开吗？ 我刚才就可以打开了啊
