### ISSUE TITLE
能真全局吗？

### ISSUE THREAD

**Issue by bitweng** [CoderJin/ssrconnect#7]
是用 network extension 接口吗？能正常代理终端吗(不额外设置)？

**Comment by CoderJin** [comment]
什麽意思 啊 沒明白你的意思？

**Comment by CoderJin** [comment]
对 用的是network extension接口 ，不是我那个能开全局的模式

**Comment by bitweng** [comment]
你应该用过 shadowsocksx 客户端吧？即使选上了“全局模式”，macOS系统的有些app仍然是不走shadowocks代理的，仍然是直连。
我想知道，你这个能否像VPN那样，能让系统所有app的流量都经过你这里

**Comment by CoderJin** [comment]
对  用了network extension  就接管了整个系统的流量啊，所有的请求都经过app

**Comment by bitweng** [comment]
好，终端也走代理对吧？
那么，这个app都支持那些加密协议？

**Comment by CoderJin** [comment]
你看看过我的ios客户端没 和他一样啊

**Comment by bitweng** [comment]
我没有用iOS手机，用Mac电脑，所以才有这些问题

**Comment by bitweng** [comment]
我购买了，有好多加密方式没有，比如 chacha20-ietf-poly1305 aes-256-gcm 。
希望有更新

**Comment by CoderJin** [comment]
后面一定会新增的，现在忙其他事情
